/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SubscribeRouteImport } from './routes/subscribe'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibrarySlugRouteImport } from './routes/library.$slug'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeRoute = SubscribeRouteImport.update({
  id: '/subscribe',
  path: '/subscribe',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/subscribe.lazy').then((d) => d.Route))
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/library.lazy').then((d) => d.Route))
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/guides.lazy').then((d) => d.Route))
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/contact.lazy').then((d) => d.Route))
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrarySlugRoute = LibrarySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LibraryRoute,
} as any).lazy(() => import('./routes/library.$slug.lazy').then((d) => d.Route))
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuidesRoute,
} as any).lazy(() => import('./routes/guides.$slug.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/guides': typeof GuidesRouteWithChildren
  '/library': typeof LibraryRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/subscribe': typeof SubscribeRoute
  '/terms': typeof TermsRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/library/$slug': typeof LibrarySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/guides': typeof GuidesRouteWithChildren
  '/library': typeof LibraryRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/subscribe': typeof SubscribeRoute
  '/terms': typeof TermsRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/library/$slug': typeof LibrarySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/guides': typeof GuidesRouteWithChildren
  '/library': typeof LibraryRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/subscribe': typeof SubscribeRoute
  '/terms': typeof TermsRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/library/$slug': typeof LibrarySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/guides'
    | '/library'
    | '/privacy'
    | '/subscribe'
    | '/terms'
    | '/guides/$slug'
    | '/library/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/guides'
    | '/library'
    | '/privacy'
    | '/subscribe'
    | '/terms'
    | '/guides/$slug'
    | '/library/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/guides'
    | '/library'
    | '/privacy'
    | '/subscribe'
    | '/terms'
    | '/guides/$slug'
    | '/library/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GuidesRoute: typeof GuidesRouteWithChildren
  LibraryRoute: typeof LibraryRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  SubscribeRoute: typeof SubscribeRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe': {
      id: '/subscribe'
      path: '/subscribe'
      fullPath: '/subscribe'
      preLoaderRoute: typeof SubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$slug': {
      id: '/library/$slug'
      path: '/$slug'
      fullPath: '/library/$slug'
      preLoaderRoute: typeof LibrarySlugRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof GuidesRoute
    }
  }
}

interface GuidesRouteChildren {
  GuidesSlugRoute: typeof GuidesSlugRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesSlugRoute: GuidesSlugRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

interface LibraryRouteChildren {
  LibrarySlugRoute: typeof LibrarySlugRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibrarySlugRoute: LibrarySlugRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GuidesRoute: GuidesRouteWithChildren,
  LibraryRoute: LibraryRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  SubscribeRoute: SubscribeRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
